language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - 7.4
  - nightly

before_script: composer install -n --dev

script:
  - vendor/bin/phpcs
  - vendor/bin/phpunit --coverage-text

allow_failures:
  - php: nightly
